// Для auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const SUCCESS = 'SUCCESS'
export const ERROR_MESSAGE_AUTH = 'ERROR_MESSAGE_AUTH'
export const PUSH_FILTERS = 'PUSH_FILTERS'

// Для admin
export const PUSH_USERS = 'PUSH_USERS'
export const PUSH_SELECTS = 'PUSH_SELECTS'
export const CHANGE_CONDITION = 'CHANGE_CONDITION'

// Для teacher
export const SUCCESS_MAIN = 'SUCCESS_MAIN'
export const SUCCESS_TASK_ADDITION = 'SUCCESS_TASK_ADDITION'
export const SUCCESS_CREATE_DATA = 'SUCCESS_CREATE_DATA'
export const SUCCESS_CREATE = 'SUCCESS_CREATE'
export const SUCCESS_CREATE_REPOSITORY = 'SUCCESS_CREATE_REPOSITORY'
export const SUCCESS_CREATE_REPOSITORY_END = 'SUCCESS_CREATE_REPOSITORY_END' 

// Для student

// Универсально
export const SUCCESS_PROFILE = 'SUCCESS_PROFILE'
export const SUCCESS_TASK = 'SUCCESS_TASK'
export const SUCCESS_TASKS = 'SUCCESS_TASKS'
export const ERROR_WINDOW = 'ERROR_WINDOW'
export const LOADING_START = 'LOADING_START'
export const SUCCESS_REPOSITORY = 'SUCCESS_REPOSITORY'
export const SUCCESS_SUBJECT_FULL = 'SUCCESS_SUBJECT_FULL'